name: catbreeds
description: "Flutter app to explore cat breeds using The Cat API. Clean Architecture, feature-first modular structure and Riverpod for state management."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  go_router: ^14.6.3
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.5
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/